# Generated by Django 5.0.3 on 2024-03-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra pradesh'), ('Tamil Nadu', 'Tamil Nadu')], max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('profileimg', models.ImageField(blank=True, upload_to='images')),
                ('document', models.FileField(blank=True, upload_to='mydocs')),
            ],
        ),
    ]
